# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'info_en.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_WeatherWindow(object):
    def setupUiw(self, WeatherWindow):
        if not WeatherWindow.objectName():
            WeatherWindow.setObjectName(u"WeatherWindow")
        WeatherWindow.resize(400, 190)
        WeatherWindow.setMinimumSize(QSize(400, 190))
        WeatherWindow.setMaximumSize(QSize(400, 190))
        self.citylbl = QLabel(WeatherWindow)
        self.citylbl.setObjectName(u"citylbl")
        self.citylbl.setGeometry(QRect(0, 0, 400, 50))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush1 = QBrush(QColor(255, 255, 255, 128))
        brush1.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush1)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush1)
#endif
        brush2 = QBrush(QColor(120, 120, 120, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 128))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush3)
#endif
        self.citylbl.setPalette(palette)
        font = QFont()
        font.setFamily(u"Yandex Sans Text Medium")
        font.setPointSize(25)
        self.citylbl.setFont(font)
        self.citylbl.setTextFormat(Qt.AutoText)
        self.citylbl.setAlignment(Qt.AlignCenter)
        self.templbl = QLabel(WeatherWindow)
        self.templbl.setObjectName(u"templbl")
        self.templbl.setGeometry(QRect(104, 70, 31, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.templbl.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Yandex Sans Text Medium")
        font1.setPointSize(20)
        self.templbl.setFont(font1)
        self.templbl.setAlignment(Qt.AlignCenter)
        self.weatherlbl = QLabel(WeatherWindow)
        self.weatherlbl.setObjectName(u"weatherlbl")
        self.weatherlbl.setGeometry(QRect(0, 40, 400, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.weatherlbl.setPalette(palette2)
        font2 = QFont()
        font2.setFamily(u"Yandex Sans Text Medium")
        font2.setPointSize(14)
        self.weatherlbl.setFont(font2)
        self.weatherlbl.setAlignment(Qt.AlignCenter)
        self.feelslike = QLabel(WeatherWindow)
        self.feelslike.setObjectName(u"feelslike")
        self.feelslike.setGeometry(QRect(180, 75, 91, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.feelslike.setPalette(palette3)
        self.feelslike.setFont(font2)
        self.feelslike.setAlignment(Qt.AlignCenter)
        self.feelslbl = QLabel(WeatherWindow)
        self.feelslbl.setObjectName(u"feelslbl")
        self.feelslbl.setGeometry(QRect(268, 75, 31, 21))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.feelslbl.setPalette(palette4)
        self.feelslbl.setFont(font2)
        self.feelslbl.setAlignment(Qt.AlignCenter)
        self.bg = QLabel(WeatherWindow)
        self.bg.setObjectName(u"bg")
        self.bg.setGeometry(QRect(0, 0, 411, 211))
        self.bg.setPixmap(QPixmap(u"icons/background.jpg"))
        self.bg.setScaledContents(True)
        self.clbl = QLabel(WeatherWindow)
        self.clbl.setObjectName(u"clbl")
        self.clbl.setGeometry(QRect(130, 70, 41, 31))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.clbl.setPalette(palette5)
        self.clbl.setFont(font1)
        self.clbl.setAlignment(Qt.AlignCenter)
        self.clbl_2 = QLabel(WeatherWindow)
        self.clbl_2.setObjectName(u"clbl_2")
        self.clbl_2.setGeometry(QRect(291, 75, 31, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.clbl_2.setPalette(palette6)
        self.clbl_2.setFont(font2)
        self.clbl_2.setAlignment(Qt.AlignCenter)
        self.windspeed = QLabel(WeatherWindow)
        self.windspeed.setObjectName(u"windspeed")
        self.windspeed.setGeometry(QRect(35, 110, 121, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.windspeed.setPalette(palette7)
        self.windspeed.setFont(font2)
        self.windspeed.setAlignment(Qt.AlignCenter)
        self.speedlbl = QLabel(WeatherWindow)
        self.speedlbl.setObjectName(u"speedlbl")
        self.speedlbl.setGeometry(QRect(152, 110, 21, 20))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.speedlbl.setPalette(palette8)
        self.speedlbl.setFont(font2)
        self.speedlbl.setAlignment(Qt.AlignCenter)
        self.mslbl = QLabel(WeatherWindow)
        self.mslbl.setObjectName(u"mslbl")
        self.mslbl.setGeometry(QRect(167, 110, 47, 20))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.mslbl.setPalette(palette9)
        self.mslbl.setFont(font2)
        self.mslbl.setAlignment(Qt.AlignCenter)
        self.airhumidity = QLabel(WeatherWindow)
        self.airhumidity.setObjectName(u"airhumidity")
        self.airhumidity.setGeometry(QRect(211, 110, 121, 20))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.airhumidity.setPalette(palette10)
        self.airhumidity.setFont(font2)
        self.airhumidity.setAlignment(Qt.AlignCenter)
        self.humlbl = QLabel(WeatherWindow)
        self.humlbl.setObjectName(u"humlbl")
        self.humlbl.setGeometry(QRect(324, 110, 31, 21))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.humlbl.setPalette(palette11)
        self.humlbl.setFont(font2)
        self.humlbl.setAlignment(Qt.AlignCenter)
        self.procent = QLabel(WeatherWindow)
        self.procent.setObjectName(u"procent")
        self.procent.setGeometry(QRect(346, 110, 21, 20))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.procent.setPalette(palette12)
        self.procent.setFont(font2)
        self.procent.setAlignment(Qt.AlignCenter)
        self.pressure = QLabel(WeatherWindow)
        self.pressure.setObjectName(u"pressure")
        self.pressure.setGeometry(QRect(97, 140, 91, 20))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.pressure.setPalette(palette13)
        self.pressure.setFont(font2)
        self.pressure.setAlignment(Qt.AlignCenter)
        self.preslbl = QLabel(WeatherWindow)
        self.preslbl.setObjectName(u"preslbl")
        self.preslbl.setGeometry(QRect(183, 140, 31, 20))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.preslbl.setPalette(palette14)
        self.preslbl.setFont(font2)
        self.preslbl.setAlignment(Qt.AlignCenter)
        self.mm = QLabel(WeatherWindow)
        self.mm.setObjectName(u"mm")
        self.mm.setGeometry(QRect(208, 140, 111, 21))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush2)
        self.mm.setPalette(palette15)
        self.mm.setFont(font2)
        self.mm.setAlignment(Qt.AlignCenter)
        self.bg.raise_()
        self.citylbl.raise_()
        self.feelslbl.raise_()
        self.feelslike.raise_()
        self.templbl.raise_()
        self.weatherlbl.raise_()
        self.clbl.raise_()
        self.clbl_2.raise_()
        self.windspeed.raise_()
        self.speedlbl.raise_()
        self.mslbl.raise_()
        self.airhumidity.raise_()
        self.humlbl.raise_()
        self.procent.raise_()
        self.pressure.raise_()
        self.preslbl.raise_()
        self.mm.raise_()

        self.retranslateUi(WeatherWindow)

        QMetaObject.connectSlotsByName(WeatherWindow)
    # setupUi

    def retranslateUi(self, WeatherWindow):
        WeatherWindow.setWindowTitle(QCoreApplication.translate("WeatherWindow", u"Form", None))
        self.citylbl.setText(QCoreApplication.translate("WeatherWindow", u"Your city", None))
        self.templbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.weatherlbl.setText(QCoreApplication.translate("WeatherWindow", u"Weather", None))
        self.feelslike.setText(QCoreApplication.translate("WeatherWindow", u"Feels like:", None))
        self.feelslbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.bg.setText("")
        self.clbl.setText(QCoreApplication.translate("WeatherWindow", u"\u00b0\u0421", None))
        self.clbl_2.setText(QCoreApplication.translate("WeatherWindow", u"\u00b0\u0421", None))
        self.windspeed.setText(QCoreApplication.translate("WeatherWindow", u"Wind speed:", None))
        self.speedlbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.mslbl.setText(QCoreApplication.translate("WeatherWindow", u"m/s", None))
        self.airhumidity.setText(QCoreApplication.translate("WeatherWindow", u"Air humidity:", None))
        self.humlbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.procent.setText(QCoreApplication.translate("WeatherWindow", u"%", None))
        self.pressure.setText(QCoreApplication.translate("WeatherWindow", u"Pressure:", None))
        self.preslbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.mm.setText(QCoreApplication.translate("WeatherWindow", u"mm Hg. Art.", None))
    # retranslateUi

