from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_WeatherWindow(object):
    def setupUiw(self, WeatherWindow):
        if not WeatherWindow.objectName():
            WeatherWindow.setObjectName(u"WeatherWindow")
        WeatherWindow.resize(400, 190)
        WeatherWindow.setMinimumSize(QSize(400, 190))
        WeatherWindow.setMaximumSize(QSize(400, 190))
        self.citylbl = QLabel(WeatherWindow)
        self.citylbl.setObjectName(u"citylbl")
        self.citylbl.setGeometry(QRect(0, 0, 400, 50))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        self.citylbl.setPalette(palette)
        font = QFont()
        font.setFamily(u"Yandex Sans Text Medium")
        font.setPointSize(25)
        self.citylbl.setFont(font)
        self.citylbl.setTextFormat(Qt.AutoText)
        self.citylbl.setAlignment(Qt.AlignCenter)
        self.templbl = QLabel(WeatherWindow)
        self.templbl.setObjectName(u"templbl")
        self.templbl.setGeometry(QRect(67, 70, 31, 31))
        self.templbl.setPalette(palette)
        font1 = QFont()
        font1.setFamily(u"Yandex Sans Text Medium")
        font1.setPointSize(20)
        self.templbl.setFont(font1)
        self.templbl.setAlignment(Qt.AlignCenter)
        self.weatherlbl = QLabel(WeatherWindow)
        self.weatherlbl.setObjectName(u"weatherlbl")
        self.weatherlbl.setGeometry(QRect(0, 40, 400, 31))
        self.weatherlbl.setPalette(palette)
        font2 = QFont()
        font2.setFamily(u"Yandex Sans Text Medium")
        font2.setPointSize(14)
        self.weatherlbl.setFont(font2)
        self.weatherlbl.setAlignment(Qt.AlignCenter)
        self.feelslike = QLabel(WeatherWindow)
        self.feelslike.setObjectName(u"feelslike")
        self.feelslike.setGeometry(QRect(135, 75, 151, 21))
        self.feelslike.setPalette(palette)
        self.feelslike.setFont(font2)
        self.feelslike.setAlignment(Qt.AlignCenter)
        self.feelslbl = QLabel(WeatherWindow)
        self.feelslbl.setObjectName(u"feelslbl")
        self.feelslbl.setGeometry(QRect(280, 75, 31, 21))
        self.feelslbl.setPalette(palette)
        self.feelslbl.setFont(font2)
        self.feelslbl.setAlignment(Qt.AlignCenter)
        self.bg = QLabel(WeatherWindow)
        self.bg.setObjectName(u"bg")
        self.bg.setGeometry(QRect(0, 0, 411, 211))
        self.bg.setPixmap(QPixmap(u"../../../../Users/kindast/Desktop/weather/GUI Version (not finished)/icons/background.jpg"))
        self.bg.setScaledContents(True)
        self.clbl = QLabel(WeatherWindow)
        self.clbl.setObjectName(u"clbl")
        self.clbl.setGeometry(QRect(93, 70, 41, 31))
        self.clbl.setPalette(palette)
        self.clbl.setFont(font1)
        self.clbl.setAlignment(Qt.AlignCenter)
        self.clbl_2 = QLabel(WeatherWindow)
        self.clbl_2.setObjectName(u"clbl_2")
        self.clbl_2.setGeometry(QRect(303, 75, 31, 21))
        self.clbl_2.setPalette(palette)
        self.clbl_2.setFont(font2)
        self.clbl_2.setAlignment(Qt.AlignCenter)
        self.windspeed = QLabel(WeatherWindow)
        self.windspeed.setObjectName(u"windspeed")
        self.windspeed.setGeometry(QRect(13, 110, 151, 21))
        self.windspeed.setPalette(palette)
        self.windspeed.setFont(font2)
        self.windspeed.setAlignment(Qt.AlignCenter)
        self.speedlbl = QLabel(WeatherWindow)
        self.speedlbl.setObjectName(u"speedlbl")
        self.speedlbl.setGeometry(QRect(163, 110, 31, 20))
        self.speedlbl.setPalette(palette)
        self.speedlbl.setFont(font2)
        self.speedlbl.setAlignment(Qt.AlignCenter)
        self.mslbl = QLabel(WeatherWindow)
        self.mslbl.setObjectName(u"mslbl")
        self.mslbl.setGeometry(QRect(188, 110, 47, 20))
        self.mslbl.setPalette(palette)
        self.mslbl.setFont(font2)
        self.mslbl.setAlignment(Qt.AlignCenter)
        self.airhumidity = QLabel(WeatherWindow)
        self.airhumidity.setObjectName(u"airhumidity")
        self.airhumidity.setGeometry(QRect(233, 110, 121, 20))
        self.airhumidity.setPalette(palette)
        self.airhumidity.setFont(font2)
        self.airhumidity.setAlignment(Qt.AlignCenter)
        self.humlbl = QLabel(WeatherWindow)
        self.humlbl.setObjectName(u"humlbl")
        self.humlbl.setGeometry(QRect(344, 110, 31, 21))
        self.humlbl.setPalette(palette)
        self.humlbl.setFont(font2)
        self.humlbl.setAlignment(Qt.AlignCenter)
        self.procent = QLabel(WeatherWindow)
        self.procent.setObjectName(u"procent")
        self.procent.setGeometry(QRect(369, 110, 21, 20))
        self.procent.setPalette(palette)
        self.procent.setFont(font2)
        self.procent.setAlignment(Qt.AlignCenter)
        self.pressure = QLabel(WeatherWindow)
        self.pressure.setObjectName(u"pressure")
        self.pressure.setGeometry(QRect(84, 140, 101, 20))
        self.pressure.setPalette(palette)
        self.pressure.setFont(font2)
        self.pressure.setAlignment(Qt.AlignCenter)
        self.preslbl = QLabel(WeatherWindow)
        self.preslbl.setObjectName(u"preslbl")
        self.preslbl.setGeometry(QRect(186, 140, 33, 20))
        self.preslbl.setPalette(palette)
        self.preslbl.setFont(font2)
        self.preslbl.setAlignment(Qt.AlignCenter)
        self.mm = QLabel(WeatherWindow)
        self.mm.setObjectName(u"mm")
        self.mm.setGeometry(QRect(210, 140, 111, 21))
        self.mm.setPalette(palette)
        self.mm.setFont(font2)
        self.mm.setAlignment(Qt.AlignCenter)
        self.bg.raise_()
        self.citylbl.raise_()
        self.feelslbl.raise_()
        self.feelslike.raise_()
        self.templbl.raise_()
        self.weatherlbl.raise_()
        self.clbl.raise_()
        self.clbl_2.raise_()
        self.windspeed.raise_()
        self.speedlbl.raise_()
        self.mslbl.raise_()
        self.airhumidity.raise_()
        self.humlbl.raise_()
        self.procent.raise_()
        self.pressure.raise_()
        self.preslbl.raise_()
        self.mm.raise_()

        self.retranslateUi(WeatherWindow)

        QMetaObject.connectSlotsByName(WeatherWindow)
    # setupUi

    def retranslateUi(self, WeatherWindow):
        WeatherWindow.setWindowTitle(QCoreApplication.translate("WeatherWindow", u"Form", None))
        self.citylbl.setText(QCoreApplication.translate("WeatherWindow", u"\u0412\u0430\u0448 \u0433\u043e\u0440\u043e\u0434", None))
        self.templbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.weatherlbl.setText(QCoreApplication.translate("WeatherWindow", u"\u041f\u043e\u0433\u043e\u0434\u0430", None))
        self.feelslike.setText(QCoreApplication.translate("WeatherWindow", u"\u041e\u0449\u0443\u0449\u0430\u0435\u0442\u0441\u044f \u043a\u0430\u043a:", None))
        self.feelslbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.bg.setText("")
        self.clbl.setText(QCoreApplication.translate("WeatherWindow", u"\u00b0\u0421", None))
        self.clbl_2.setText(QCoreApplication.translate("WeatherWindow", u"\u00b0\u0421", None))
        self.windspeed.setText(QCoreApplication.translate("WeatherWindow", u"\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0432\u0435\u0442\u0440\u0430:", None))
        self.speedlbl.setText(QCoreApplication.translate("WeatherWindow", u"0.0", None))
        self.mslbl.setText(QCoreApplication.translate("WeatherWindow", u"\u043c/\u0441", None))
        self.airhumidity.setText(QCoreApplication.translate("WeatherWindow", u"\u0412\u043b\u0430\u0436\u043d\u043e\u0441\u0442\u044c:", None))
        self.humlbl.setText(QCoreApplication.translate("WeatherWindow", u"0", None))
        self.procent.setText(QCoreApplication.translate("WeatherWindow", u"%", None))
        self.pressure.setText(QCoreApplication.translate("WeatherWindow", u"\u0414\u0430\u0432\u043b\u0435\u043d\u0438\u0435:", None))
        self.preslbl.setText(QCoreApplication.translate("WeatherWindow", u"000", None))
        self.mm.setText(QCoreApplication.translate("WeatherWindow", u"\u043c\u043c \u0440\u0442. \u0441\u0442.", None))
    # retranslateUi

